### ISSUE TITLE
Handle possible hash map and vector allocation failures

### ISSUE THREAD

**Issue by czapek1337** [lyre-os/lyre#34]
Currently we don't handle any allocation failures that could occur when using hash maps and vectors, which is obviously bad. We should change that and update existing code to take advantage of that to fail gracefully and improve kernel stability.

**Comment by TheChosenOne666** [comment]
> Currently we don't handle any allocation failures that could occur when using hash maps and vectors, which is obviously bad. We should change that and update existing code to take advantage of that to fail gracefully and improve kernel stability.

Unless you wanna send a PR good luck with that.

**Comment by czapek1337** [comment]
> Unless you wanna send a PR good luck with that.

I created that issue because I wanted to point out the issue at the time, mainly because I wrote most of the code and was unhappy with how it was. That is not a bug report or a request to fix it of any kind.

**Comment by RaidTheWeb** [comment]
how important

**Comment by mintsuki** [comment]
I wrote the hashmap code myself, for the record.
