### ISSUE TITLE
Mlibc script suggestion

### ISSUE THREAD

**Issue by safinsingh** [lyre-os/lyre#6]
https://github.com/lyre-os/lyre/blob/839b0691aced6dd93cb4195878536a3ac7065d94/make-mlibc.sh#L5-L9

You can replace `( && \` and co. with:

```bash
[ -d mlibc-workdir ] || {
    mkdir mlibc-workdir
    tar -xf mlibc.tar.gz -C mlibc-workdir --strip-components=1
    cd mlibc-workdir
    patch -p2 < ../patches/mlibc/mlibc.patch
}
```

**Comment by mintsuki** [comment]
LGTM, if you send a PR referencing this issue I'll merge it.
