### ISSUE TITLE
build error on Debian 11 with root, but a non root user built OK

### ISSUE THREAD

**Issue by seven1240** [Lyre-OS/Lyre#66]
```
uname -a
Linux 5.10.0-9-amd64 #1 SMP Debian 5.10.70-1 (2021-09-30) x86_64 GNU/Linux
```

[lyre.build.err.txt](https://github.com/Lyre-OS/Lyre/files/14337592/lyre.build.err.txt)

Lyre looks great and I successfully built with a non-root user but build with root user failed. I attached the who log on console.

Looks like some ACL's related? I see some ACL related errors.

```
Setting access ACL "u::rwx,g::r-x,g:wheel:r-x,g:adm:r-x,g:4294967295:r-x,g:4294967295:r-x,m::r-x,o::r-x" on /var/log/journal failed: Invalid argument
```

```
commit bb260fcc1f685264ed08f6ea4632156c5ee1f6d7 (HEAD -> trunk, tag: nightly-2024-02-18, origin/trunk, origin/HEAD)
Author: mintsuki <mintsuki@protonmail.com>
Date:   Sat Feb 17 13:10:20 2024 +0100

    ports/mlibc: Bump revision
```

Thanks.

**Comment by mintsuki** [comment]
Thanks for reporting this.

Jinx doesn't support running as root, and this is something that somehow a lot of people attempt to do, so I have updated Jinx to fail to run if attempted to run as root.

**Comment by seven1240** [comment]
Nice. Thanks.

And I add the commit for reference here: https://github.com/mintsuki/jinx/commit/f5869a6252e11b8fd0113f382c2cdaa78e0b52fa
