### ISSUE TITLE
!!!

### ISSUE THREAD

**Issue by AnatoliyLl** [Lyre-OS/Lyre#67]
F*ck you @mintsuki. My previous account(@Anatoliy6463) was hidden because of YOU!!!

**Comment by Dennisbonke** [comment]
And you deserved that for your behavior.

**Comment by AnatoliyLl** [comment]
@mintsuki, I will stop hating if you will star Andesaurux, then I will star your repos(Limine and Lyre)

**Comment by AnatoliyLl** [comment]
> And you deserved that for your behavior.

And you also deserve to be hidden from GitHub 😂.

**Comment by 48cf** [comment]
![image](https://github.com/Lyre-OS/Lyre/assets/32851089/4d8a7fd5-79c9-4f05-8b0e-057d56fb13bb)
...and you shall be banned again

**Comment by AnatoliyLl** [comment]
> ![image](https://github.com/Lyre-OS/Lyre/assets/32851089/4d8a7fd5-79c9-4f05-8b0e-057d56fb13bb)
> ...and you shall be banned again

No!!!

**Comment by AnatoliyLl** [comment]
No!! Pls

**Comment by AnatoliyLl** [comment]
I will star lyre, pls don't ban me

**Comment by AnatoliyLl** [comment]
I did same with mintsuki, he wasn't blocked, I will also be not blocked

**Comment by AnatoliyLl** [comment]
![Screenshot_20240229_000148.jpg](https://github.com/Lyre-OS/Lyre/assets/160674434/093a53b9-1102-4cbf-b98f-3a8426c2e7d1)

**Comment by AnatoliyLl** [comment]
> ![Screenshot_20240229_000148.jpg](https://github.com/Lyre-OS/Lyre/assets/160674434/093a53b9-1102-4cbf-b98f-3a8426c2e7d1)
> 
> 

You are banned!
